### ISSUE TITLE
checkable object status report for unexpected checkable object module.oke.var.cni_type

### ISSUE THREAD

**Issue by brasrox** [oracle-quickstart/oke-base#37]
did a ```terraform destroy -refresh=false``` and got a crash here

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!



checkable object status report for unexpected checkable object module.oke.var.cni_type

goroutine 3519 [running]:

runtime/debug.Stack()

	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x5e

runtime/debug.PrintStack()

	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:16 +0x13

github.com/hashicorp/terraform/internal/logging.PanicHandler()

	/home/runner/work/terraform/terraform/internal/logging/panic.go:58 +0x13b

panic({0x2b94ec0?, 0xc0008eaf50?})

	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:920 +0x270

github.com/hashicorp/terraform/internal/checks.(*State).reportCheckResult(0xc001113770, {0x390a1d0, 0xc006cbfe30}, 0xc00027d400?, 0x0, 0x50)

	/home/runner/work/terraform/terraform/internal/checks/state_report.go:106 +0x345

github.com/hashicorp/terraform/internal/checks.(*State).ReportCheckResult(0x2fcdc40?, {0x390a1d0?, 0xc006cbfe30?}, 0xc000a5f6a8?, 0x1?, 0x1?)

	/home/runner/work/terraform/terraform/internal/checks/state_report.go:71 +0xc5

github.com/hashicorp/terraform/internal/terraform.evalVariableValidations({{0xc00207f240, 0x1, 0x1}, {{}, {0xc000f9cb70, 0x8}}}, 0xc000e3bba0, {0x3905a08, 0xc000640960}, {0x3922940, ...})

	/home/runner/work/terraform/terraform/internal/terraform/eval_variable.go:252 +0xb52

github.com/hashicorp/terraform/internal/terraform.(*nodeModuleVariable).Execute(0xc000960960, {0x3922940, 0xc000d7e9a0}, 0x5)

	/home/runner/work/terraform/terraform/internal/terraform/node_module_variable.go:198 +0x3f1

github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc0076677a0, {0x3922940, 0xc000d7e9a0}, {0x7fa747d30000, 0xc000960960})

	/home/runner/work/terraform/terraform/internal/terraform/graph_walk_context.go:143 +0xbe

github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x2f09cc0, 0xc000960960})

	/home/runner/work/terraform/terraform/internal/terraform/graph.go:78 +0x375

github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc000960a20, {0x2f09cc0, 0xc000960960}, 0xc0067a5dc0)

	/home/runner/work/terraform/terraform/internal/dag/walk.go:384 +0x2e5

created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update in goroutine 3175

	/home/runner/work/terraform/terraform/internal/dag/walk.go:307 +0xde8


```
any ideas?

**Comment by brasrox** [comment]
```
terraform version

Terraform v1.6.1

on linux_amd64

+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2

+ provider registry.terraform.io/hashicorp/helm v2.9.0

+ provider registry.terraform.io/hashicorp/kubernetes v2.20.0

+ provider registry.terraform.io/hashicorp/local v2.4.0

+ provider registry.terraform.io/hashicorp/random v3.5.1

+ provider registry.terraform.io/hashicorp/tls v4.0.4

+ provider registry.terraform.io/oracle/oci v4.121.0


```

**Comment by brasrox** [comment]
After upgrading terraform to 1.6.2 this issue has been resolved.
:D
